image: machimachi/docker-node-with-chrome

test:
  script:
    - npm install --silent && npm prune
    - npm run test
    - ng lint
    - npm run build:prod

deploy:
  script:
    - npm install --silent && npm prune
    - npm run publish
  only:
    - master
